#create Mysql YamlFile
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql
  namespace: expense
  labels:
    project: robo
    state: qa
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: robo
      state: qa
      tier: db
  template:
    metadata:
      labels:
        project: robo
        state: qa
        tier: db
    spec:
      containers:
        - name: mysql
          image: kdprasad028/mysql:v1
---
#create Service to commu mysql Pods
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    project: robo
    state: qa
    tier: db
  ports:
  - name: mysql-port
    protocol: TCP
    port: 3306
    targetPort: 3306
         