# Create cluster
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense-dev
  region: us-esat-1

managedNodeGroups:
- name: spot
  instanceType: m5.large
  desiredCapacity: 3
  spot: true

#eksctl create cluster -f cluster.yaml