# Create cluster
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense-dev
  region: us-east-1

managedNodeGroups:
- name: spot
  instanceType: m5.large
  desiredCapacity: 2
  spot: true

#eksctl create cluster -f cluster.yaml