#create role to access our esxpense cluster for new user:
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: expense
  name: rl-pod
rules:
- apiGroups: [""] # "" indicates the core API group, contains pods, services, namespaces, for accessing kubernets API.
  resources: ["pods"]   #only pods
  verbs: ["get", "watch", "list"]
---
#create RoleBinding 
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: rb-pod
  namespace: expense
subjects:
# You can specify more than one "subject"
- kind: User
  name: suresh # "name" is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: rl-pod # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
---
#create role to access our esxpense cluster for new user:
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: expense
  name: role-all
rules:
- apiGroups: [""] # "" indicates the core API group, contains pods, services, namespaces, for accessing kubernets API.
  resources: ["*"]   #only pods
  verbs: ["*"]
---
#create RoleBinding 
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: rb-pod2
  namespace: expense
subjects:
# You can specify more than one "subject"
- kind: User
  name: ramesh # "name" is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: role-all # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: clstr-reader2
  namespace: expense
rules:
- apiGroups: [""]
  #
  # at the HTTP level, the name of the resource for accessing Secret
  # objects is "secrets"
  resources: ["*"] 
  # resources: ["nodes", "persistentvolumes", "namespaces"]
  # verbs: ["get", "watch", "list", "create", "patch", "update"]
  verbs: ["*"]
---
#create Cluster RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-binding-ram
  namespace: expense
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clstr-reader2
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: ramesh
---
#Suresh Clusetr
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: clstr-reader
  namespace: expense
rules:
- apiGroups: [""]
  #
  # at the HTTP level, the name of the resource for accessing Secret
  # objects is "secrets"
  resources: ["nodes", "persistentvolumes", "namespaces"] 
  verbs: ["get", "watch", "list", "create", "patch", "update"]
---
#create Cluster RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-grantor-binding
  namespace: expense
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clstr-reader
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: suresh
