apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica
  labels:
    project: robo
    app: frontend
    tier: stage
spec:
  replicas: 2
  selector:
   matchLabels:
      project: nginx
      environment: dev
  template:
    metadata:
      labels:
        project: nginx
        environment: dev
      spec:
        containers:
        - name: nginx
          images: nginx:stable-perl
            