apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica
  labels:
    project: robo
    app: frontend
    tier: stage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      tier: stage
  template:
    metadata:
      labels:
        app: frontend
        tier: stage
    spec:
        containers:
        - name: nginx
          image: nginx:stable-perl
            