apiVersion: app/v1
kind: Deployment
metadata:
  name: pod-dep
  labels:
    app: backend
    module: qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      module: qa
  template:
    metadata:
      labels:
        app: backend
        module: qa
  spec:
    containers:
      - name: dep-nginx
        images: nginx:almalinux
