apiVersion: v1
kind: Pod
metadata:
  name: multi-cont
  lables:
    project: nginx
    environment: dev
spec: 
  containers:
    - name: nginx-1
      image: nginx
    - name: nginx-2
      image: nginx:alpine
