apiVersion: v1
kind: Pod
metadata:
  name: with-affinity-preferred-weight
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: hardware #our key
            operator: In
            values:
            - gpu #our value
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: label-1  #change 
            operator: In
            values:
            - key-1 # change
      - weight: 50
        preference:
          matchExpressions:
          - key: label-2  # change
            operator: In
            values:
            - key-2   # change
  containers:
  - name: nginx
    image: nginx:stable-perl
