#create ConfigMap for DB_HOST=mysql
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: expense
data:
  DB_HOST: "mysql-svc-normal"
---
#Create Backend Deployment set code
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
      project: robo
      tier: app
      environment: qa
spec:
  replicas: 2
  selector:
    matchLabels:
      project: robo
      tier: app
      environment: qa
  template:
    metadata:
      labels:
        project: robo
        tier: app
        environment: qa
    spec:
      containers:
      - name: backend
        image: kdprasad028/backend:v1
        envFrom:
        - configMapRef:
            name: backend-config
---
#Create Service
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    project: robo
    tier: app
    environment: qa
  ports:
  - name: backend-port
    protocol: TCP
    port: 8080
    targetPort: 8080 
