apiVersion: apps/v1
kind: ConfigMap
metadata: 
  name: backend
  namespace: expense
data:
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend
  namespace: expense
  labels:
    project: expense
    component: backend
    tier: app
spec:
  replicas: 2
  selector:
    matchLabels:
      project: expense
      component: backend
      tier: app
  template:
    metadata:
      labels:
        project: expense
        component: backend
        tier: app
    spec:
      containers:
        - name: backend
          image: kdprasad028/backend:v1
---
apiVersion: v1
kind: Service
metadata: 
  name: backend
  namespace: expense
  labels:
    project: expense
    component: backend
    tier: app
spec:
  selector:
    name: backend
  ports:
    - name: backend-port
      protocol: TCP
      port: 8080
      targetPort: 8080