apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql
  namespace: expense
  labels:
    project: expense
    component: mysql
    tier: db
spec:
  replicas: 2
  selector:
    matchLabels:
      project: expense
      component: mysql
      tier: db
  template:
    metadata:
      labels:
        project: expense
        component: mysql
        tier: db
    spec:
      containers:
        - name: mysql
          image: kdprasad028/mysql:v1
---
apiVersion: v1
kind: Service
metadata: 
  name: mysql
  namespace: expense
  labels:
    project: expense
    component: mysql
    tier: db
spec:
  selector:
     project: expense
     component: mysql
     tier: db
  ports:
    - name: db-port
      protocol: TCP
      port: 3306
      targetPort: 3306