#create Service to commu backend Pods
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    project: robo
    state: qa
  ports:
  - name: backend-port
    protocol: TCP
    port: {{ .Values.service.servicePort }}
    targetPort: 80
  type: {{ .Values.service.type }}