#create ConfigMap for DB_HOST=mysql
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: expense  #must specify namespace
data:
  DB_HOST: mysql  #in our backend dockerfile, we have environment variable of DB_HOST
---
#create backend YamlFile
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend
  namespace: expense
  labels:
    project: robo
    state: qa
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      project: robo
      state: qa
      tier: backend
  template:
    metadata:
      labels:
        project: robo
        state: qa
        tier: backend
    spec:
      containers:
        - name: backend
          image: kdprasad028/backend:v1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:            #limits should be greater than or equal to requests
              cpu: 100m
              memory: 128Mi
          envFrom:
           - configMapRef:
               name: backend-config
---
#create Service to commu backend Pods
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    project: robo
    state: qa
    tier: backend
  ports:
  - name: backend-port
    protocol: TCP
    port: 8080
    targetPort: 8080
---
#create HPA
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: expense
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 5
