#create backend YamlFile
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend
  namespace: expense
  labels:
    project: robo
    state: qa
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: robo
      state: qa
      tier: backend
  template:
    metadata:
      labels:
        project: robo
        state: qa
        tier: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.deployment.imageName }} 
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:            #limits should be greater than or equal to requests
              cpu: 100m
              memory: 128Mi