apiVersion: v1
kind: secret
metadata:
  name: secret-pod
type: opaque
data:
  username: ZWMyLXVzZXIK    # echo <USer-ID> | base64   and Decode:  echo <encoded-name> | base64 --decode
  password: RGV2T3BzMzIxCg==

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-sec
spec:  
  contaners:
    - name: nginx
      image: nginx
      envFrom:
      - secretRef:  #we can get username and password, if call like this
          name: secret-pod