apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: app
      component: backend
  template:
    metadata:
      labels:
        tier: app
        component: backend
    spec:
      container:
      - name: nginx
        image: nginx:alpine
        ports: 
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: 20Mi
          limits:
            cpu: 128m
            memory: 30Mi
          